name: Build, Run, and Deploy

env: 
  AZURE_CONTAINER_REGISTRY: devops12.azurecr.io
  MAJOR: 1
  MINOR: 0
  PATCH: 0

on: 
  push: 
    branches: feature/g1-sso-service

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 2: Login to Azure Container Registry
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      
      # Step 3: Image Versioning 
      - name: "Fetch the latest tags"
        run: | 
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v.0.0.0")
          echo "LATEST_TAG=${LATEST_TAG}" >> GITHUB_ENV

      - name: Determine increment type
        id: version_type
        run: |
          if git log -1 --pretty=%B | grep -iqE "\[MAJOR\]" || git log -1 --pretty=%B | grep -iqE "\[major\]" || git log -1 --pretty=%B | grep -iqE "\[Major\]"; then
            MAJOR=$((MAJOR + 1))
                MINOR=0
                PATCH=0
                ;
          elif git log -1 --pretty=%B | grep -iqE "\[MAJOR\]" || git log -1 --pretty=%B | grep -iqE "\[major\]" || git log -1 --pretty=%B | grep -iqE "\[Major\]"; then
            MINOR=$((MINOR + 1))
                PATCH=0
                ;
          else
            PATCH=$((PATCH + 1))
          fi

          echo "MAJOR=${MAJOR}"
          echo "MINOR=${MINOR}"
          echo "PATCH=${PATCH}"
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW_VERSION=${NEW_VERSION} " >> $GITHUB_ENV
          echo "New version: $NEW_VERSION"


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
         push: true
         tags: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}/g1-sso-service:${{ env.NEW_VERSION }}
            ${{ env.AZURE_CONTAINER_REGISTRY }}/g1-sso-service:latest

               
